FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app1

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/asp.net:8.0
WORKDIR /app1
COPY --from=build-env /app1/out .
ENTRYPOINT [ "dotnet","PlatformService.dll" ]
